# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-01-11 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_id', models.TextField()),
                ('ord_price', models.PositiveIntegerField(default=0)),
                ('ord_address', models.TextField()),
            ],
        ),
    ]
